/* Vini d’Elite — katalog Tenuta La Pergola a sommeliérské profily */
window.VINI_CATALOG = [
  {id:1,name:'San Lorenzo',region:'Piemonte · Alba',grape:'Nebbiolo d’Alba DOC · 2023',subtitle:'Šlechtic z prosluněných svahů Alby',price:null,type:'red',sweet:0,body:2,intensity:2,tone:'floral',pairing:['maso','syr'],pairingText:'Dušené hovězí, zvěřina, vyzrálé sýry',desc:'Strukturované Nebbiolo s pevnou páteří, ušlechtilou tříslovinou a dlouhým noblesním závěrem. Ve vůni spojuje cassis, fialky, koření a jemnou balsamickou stopu.',p:{ac:2,tn:2,ok:1,mn:1,sp:2,fr:'ripe',adv:2,wm:0,cx:2,mood:['dinner','cellar','gift']},aromas:['floral','spicy','fruity']},
  {id:2,name:'La Cappelletta',region:'Piemonte · Asti',grape:'Barbera d’Asti DOCG Superiore · 2019',subtitle:'Síla, elegance a vyzrálost',price:null,type:'red',sweet:0,body:2,intensity:2,tone:'woody',pairing:['maso','syr'],pairingText:'Zvěřina, pečeně, silné omáčky, vyzrálé sýry',desc:'Vznešená Barbera s plným tělem a sametovou strukturou. Zralé třešně a tmavé ovoce doplňuje růže, máta, koření, čokoláda a kultivovaná stopa zrání.',p:{ac:2,tn:1,ok:2,mn:0,sp:2,fr:'ripe',adv:2,wm:0,cx:2,mood:['dinner','cellar','gift','celebration']},aromas:['fruity','woody','spicy']},
  {id:3,name:'Masè u luv',region:'Piemonte · Asti',grape:'Barbera d’Asti DOCG · 2024',subtitle:'Šťavnatá krev italských svahů',price:null,type:'red',sweet:0,body:1,intensity:2,tone:'fruity',pairing:['maso','syr'],pairingText:'Pasta s ragú, uzeniny, pečené maso',desc:'Živá a energická Barbera s hlubokou rubínovou barvou, vůní třešní, ostružin, růže a švestek. Výrazná svěžest krásně čistí patro a drží krok s poctivou kuchyní.',p:{ac:2,tn:1,ok:0,mn:0,sp:1,fr:'ripe',adv:0,wm:0,cx:1,mood:['dinner','solo']},aromas:['fruity','floral']},
  {id:4,name:'Mondine',region:'Piemonte',grape:'Piemonte DOC Grignolino · 2024',subtitle:'Lehkost s hlubokým příběhem',price:null,type:'red',sweet:0,body:0,intensity:1,tone:'floral',pairing:['syr','ryba','solo'],pairingText:'Pasta, předkrmy, drůbež, tučnější ryby',desc:'Lehké, elegantní a velmi svěží červené. Jahoda, pomeranč, hořec a černý pepř se potkávají s jemnou mineralitou, šťavnatou tříslovinou a lehce nahořklým dozvukem.',p:{ac:2,tn:1,ok:0,mn:1,sp:1,fr:'fresh',adv:1,wm:0,cx:1,mood:['aperitiv','dinner','solo']},aromas:['fruity','spicy','mineral']},
  {id:5,name:"Cantè i 'ov",region:'Piemonte · Monferrato',grape:'Monferrato DOC Dolcetto · 2024',subtitle:'Čistá pitelnost a lidová radost',price:null,type:'red',sweet:0,body:1,intensity:1,tone:'fruity',pairing:['syr','solo'],pairingText:'Uzeniny, předkrmy, agnolotti, zeleninové polévky',desc:'Svěží a přístupné Dolcetto s rybízem, malinou, třešní a balsamickými bylinami. Je suché, ovocné a šťavnaté, s živou tříslovinou a typickou jemně mandlovou tečkou.',p:{ac:1,tn:1,ok:0,mn:0,sp:0,fr:'fresh',adv:0,wm:0,cx:1,mood:['dinner','solo','aperitiv']},aromas:['fruity','herbal']},
  {id:6,name:'Corpus Domini',region:'Piemonte · Asti',grape:'Freisa d’Asti DOC · 2024',subtitle:'Osobitý charakter starého Piemontu',price:null,type:'red',sweet:0,body:1,intensity:1,tone:'fruity',pairing:['syr','maso','solo'],pairingText:'Uzeniny, sušená šunka, tradiční předkrmy',desc:'Autentická Freisa s brusinkou, višní, květy ostružiníku a pryskyřičnou bylinnou linkou. Suchá, lehce živá a šťavnatá chuť má reaktivní tříslovinu a ovocný závěr.',p:{ac:2,tn:1,ok:0,mn:0,sp:1,fr:'fresh',adv:1,wm:0,cx:1,mood:['dinner','aperitiv','solo']},aromas:['fruity','floral','herbal']},
  {id:7,name:"Cisterna d'Asti",region:'Piemonte · Asti',grape:"Cisterna d’Asti DOC · Croatina · 2013",subtitle:'Archivní klenot a dvanáct let trpělivosti',price:null,type:'red',sweet:0,body:2,intensity:2,tone:'woody',pairing:['maso','syr'],pairingText:'Pečené hovězí, zvěřina, pecorino',desc:'Archivní Croatina s granátovými tóny, vyzrálou hloubkou a sametovou harmonií. Vařené ovoce, vanilka, dřevo a zelený pepř přecházejí do plného, persistentního závěru.',p:{ac:1,tn:2,ok:2,mn:0,sp:2,fr:'dried',adv:2,wm:0,cx:2,mood:['dinner','cellar','gift','celebration']},aromas:['woody','spicy','fruity']},
  {id:8,name:'Bric du Sivu',region:'Piemonte · Monferrato',grape:'Monferrato DOC Rosso · 2012',subtitle:'Vlajková loď z vrcholku kopce',price:null,type:'red',sweet:0,body:2,intensity:2,tone:'woody',pairing:['maso','syr','solo'],pairingText:'Zvěřina, prémiový steak, tvrdé sýry',desc:'Monumentální cuvée Barbery, Croatiny a Nebbiola zrající v barrique. Višeň, švestka, lesní plody, vanilka, pepř a kořeny tvoří pevnou strukturu a mimořádně dlouhý podpis.',p:{ac:1,tn:2,ok:2,mn:0,sp:2,fr:'dried',adv:2,wm:0,cx:2,mood:['dinner','cellar','gift','celebration','solo']},aromas:['woody','spicy','fruity']},
  {id:9,name:'Mini Fior',region:'Piemonte',grape:'Vino Spumante Brut · 12,5 %',subtitle:'Jiskrná radost v každé bublince',price:null,type:'sparkling',sweet:0,body:0,intensity:0,tone:'floral',pairing:['aperitiv','ryba','syr'],pairingText:'Aperitiv, mořské plody, lehké předkrmy, prosciutto',desc:'Čisté, osvěžující šumivé víno s jemným perlením, svěžím ovocem a květinovým tónem. Upřímná, elegantní radost pro oslavu i obyčejné odpoledne na terase.',p:{ac:2,tn:0,ok:0,mn:1,sp:0,fr:'fresh',adv:0,wm:0,cx:1,mood:['aperitiv','celebration','gift']},aromas:['floral','fruity','mineral']},
  {id:11,name:'Roero Arneis',region:'Piemonte · Roero',grape:'Roero Arneis DOCG',subtitle:'Svěžest roeronských svahů a slané pohlazení',price:null,type:'white',sweet:0,body:1,intensity:1,tone:'mineral',pairing:['ryba','aperitiv','solo'],pairingText:'Ryby, mořské plody, saláty, aperitiv',desc:'Elegantní bílé z písčitých půd a dávných mořských usazenin. Nabízí živou kyselinu, jemnou strukturu, bílé ovoce a výraznou slaně minerální linku.',p:{ac:2,tn:0,ok:0,mn:2,sp:0,fr:'fresh',adv:1,wm:0,cx:1,mood:['aperitiv','dinner','solo']},aromas:['mineral','floral','fruity']},
  {id:12,name:'Bonarda',region:'Piemonte',grape:'Piemonte DOC Bonarda',subtitle:'Přátelské víno a srdce dobrého stolu',price:null,type:'red',sweet:0,body:1,intensity:2,tone:'fruity',pairing:['maso','syr'],pairingText:'Uzeniny, pečené maso, zvěřina, tvrdé sýry',desc:'Šťavnaté a přátelské červené s třešní a švestkou, příjemnou plností a zachovanou svěžestí. Suché, měkké a harmonické víno, které se dobře sdílí u stolu.',p:{ac:1,tn:1,ok:0,mn:0,sp:0,fr:'ripe',adv:0,wm:0,cx:1,mood:['dinner','solo']},aromas:['fruity','floral']},
  {id:13,name:'Terre Alfieri Nebbiolo',region:'Piemonte · Terre Alfieri',grape:'Terre Alfieri DOCG Nebbiolo Superiore',subtitle:'Vznešený charakter tří legendárních kopců',price:null,type:'red',sweet:0,body:2,intensity:2,tone:'floral',pairing:['maso','syr'],pairingText:'Steak, dušené maso na víně, houby, tvrdé sýry',desc:'Strukturované Nebbiolo s noblesní tříslovinou, třešní, fialkou a jemným kořením. Vyžaduje pozornost a odmění dlouhým, komplexním a elegantním závěrem.',p:{ac:2,tn:2,ok:1,mn:1,sp:2,fr:'ripe',adv:2,wm:0,cx:2,mood:['dinner','cellar','gift']},aromas:['floral','spicy','fruity']}
];

window.VINI_IMAGES = {
  1:'images/wines/san-lorenzo.png',
  2:'images/wines/la-cappelletta.png',
  3:'images/wines/barbera-dasti.png',
  4:'images/wines/grignolino.png',
  5:'images/wines/dolcetto.png',
  6:'images/wines/freisa-dasti.png',
  7:'images/wines/cisterna-dasti.png',
  8:'images/wines/bric-du-sivu.png',
  9:'images/wines/mini-fior.png'
};

window.viniPriceLabel = function () { return 'Cena na dotaz'; };
window.viniContactHref = function (wine) {
  return 'mailto:obchod@vinidelite.cz?subject=' + encodeURIComponent('Poptávka vína: ' + wine.name);
};
