/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlusRouteImport } from './routes/plus'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlusIndexRouteImport } from './routes/plus.index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as PlusNahledRouteImport } from './routes/plus.nahled'
import { Route as PlusCheckoutRouteImport } from './routes/plus.checkout'
import { Route as PlusNahledIndexRouteImport } from './routes/plus.nahled.index'
import { Route as PlusNahledZapiskyRouteImport } from './routes/plus.nahled.zapisky'
import { Route as PlusNahledVideaRouteImport } from './routes/plus.nahled.videa'
import { Route as PlusNahledHlasovkyRouteImport } from './routes/plus.nahled.hlasovky'
import { Route as PlusNahledChatRouteImport } from './routes/plus.nahled.chat'
import { Route as AuthenticatedPlusZapiskyRouteImport } from './routes/_authenticated/plus.zapisky'
import { Route as AuthenticatedPlusVideaRouteImport } from './routes/_authenticated/plus.videa'
import { Route as AuthenticatedPlusUcetRouteImport } from './routes/_authenticated/plus.ucet'
import { Route as AuthenticatedPlusHlasovkyRouteImport } from './routes/_authenticated/plus.hlasovky'
import { Route as AuthenticatedPlusDashboardRouteImport } from './routes/_authenticated/plus.dashboard'
import { Route as AuthenticatedPlusChatRouteImport } from './routes/_authenticated/plus.chat'
import { Route as AuthenticatedPlusZapiskySlugRouteImport } from './routes/_authenticated/plus.zapisky.$slug'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusRoute = PlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusIndexRoute = PlusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlusRoute,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusNahledRoute = PlusNahledRouteImport.update({
  id: '/nahled',
  path: '/nahled',
  getParentRoute: () => PlusRoute,
} as any)
const PlusCheckoutRoute = PlusCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PlusRoute,
} as any)
const PlusNahledIndexRoute = PlusNahledIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlusNahledRoute,
} as any)
const PlusNahledZapiskyRoute = PlusNahledZapiskyRouteImport.update({
  id: '/zapisky',
  path: '/zapisky',
  getParentRoute: () => PlusNahledRoute,
} as any)
const PlusNahledVideaRoute = PlusNahledVideaRouteImport.update({
  id: '/videa',
  path: '/videa',
  getParentRoute: () => PlusNahledRoute,
} as any)
const PlusNahledHlasovkyRoute = PlusNahledHlasovkyRouteImport.update({
  id: '/hlasovky',
  path: '/hlasovky',
  getParentRoute: () => PlusNahledRoute,
} as any)
const PlusNahledChatRoute = PlusNahledChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PlusNahledRoute,
} as any)
const AuthenticatedPlusZapiskyRoute =
  AuthenticatedPlusZapiskyRouteImport.update({
    id: '/plus/zapisky',
    path: '/plus/zapisky',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlusVideaRoute = AuthenticatedPlusVideaRouteImport.update({
  id: '/plus/videa',
  path: '/plus/videa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlusUcetRoute = AuthenticatedPlusUcetRouteImport.update({
  id: '/plus/ucet',
  path: '/plus/ucet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlusHlasovkyRoute =
  AuthenticatedPlusHlasovkyRouteImport.update({
    id: '/plus/hlasovky',
    path: '/plus/hlasovky',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlusDashboardRoute =
  AuthenticatedPlusDashboardRouteImport.update({
    id: '/plus/dashboard',
    path: '/plus/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlusChatRoute = AuthenticatedPlusChatRouteImport.update({
  id: '/plus/chat',
  path: '/plus/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlusZapiskySlugRoute =
  AuthenticatedPlusZapiskySlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedPlusZapiskyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/plus': typeof PlusRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/plus/checkout': typeof PlusCheckoutRoute
  '/plus/nahled': typeof PlusNahledRouteWithChildren
  '/product/$handle': typeof ProductHandleRoute
  '/plus/': typeof PlusIndexRoute
  '/plus/chat': typeof AuthenticatedPlusChatRoute
  '/plus/dashboard': typeof AuthenticatedPlusDashboardRoute
  '/plus/hlasovky': typeof AuthenticatedPlusHlasovkyRoute
  '/plus/ucet': typeof AuthenticatedPlusUcetRoute
  '/plus/videa': typeof AuthenticatedPlusVideaRoute
  '/plus/zapisky': typeof AuthenticatedPlusZapiskyRouteWithChildren
  '/plus/nahled/chat': typeof PlusNahledChatRoute
  '/plus/nahled/hlasovky': typeof PlusNahledHlasovkyRoute
  '/plus/nahled/videa': typeof PlusNahledVideaRoute
  '/plus/nahled/zapisky': typeof PlusNahledZapiskyRoute
  '/plus/nahled/': typeof PlusNahledIndexRoute
  '/plus/zapisky/$slug': typeof AuthenticatedPlusZapiskySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/plus/checkout': typeof PlusCheckoutRoute
  '/product/$handle': typeof ProductHandleRoute
  '/plus': typeof PlusIndexRoute
  '/plus/chat': typeof AuthenticatedPlusChatRoute
  '/plus/dashboard': typeof AuthenticatedPlusDashboardRoute
  '/plus/hlasovky': typeof AuthenticatedPlusHlasovkyRoute
  '/plus/ucet': typeof AuthenticatedPlusUcetRoute
  '/plus/videa': typeof AuthenticatedPlusVideaRoute
  '/plus/zapisky': typeof AuthenticatedPlusZapiskyRouteWithChildren
  '/plus/nahled/chat': typeof PlusNahledChatRoute
  '/plus/nahled/hlasovky': typeof PlusNahledHlasovkyRoute
  '/plus/nahled/videa': typeof PlusNahledVideaRoute
  '/plus/nahled/zapisky': typeof PlusNahledZapiskyRoute
  '/plus/nahled': typeof PlusNahledIndexRoute
  '/plus/zapisky/$slug': typeof AuthenticatedPlusZapiskySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/plus': typeof PlusRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/plus/checkout': typeof PlusCheckoutRoute
  '/plus/nahled': typeof PlusNahledRouteWithChildren
  '/product/$handle': typeof ProductHandleRoute
  '/plus/': typeof PlusIndexRoute
  '/_authenticated/plus/chat': typeof AuthenticatedPlusChatRoute
  '/_authenticated/plus/dashboard': typeof AuthenticatedPlusDashboardRoute
  '/_authenticated/plus/hlasovky': typeof AuthenticatedPlusHlasovkyRoute
  '/_authenticated/plus/ucet': typeof AuthenticatedPlusUcetRoute
  '/_authenticated/plus/videa': typeof AuthenticatedPlusVideaRoute
  '/_authenticated/plus/zapisky': typeof AuthenticatedPlusZapiskyRouteWithChildren
  '/plus/nahled/chat': typeof PlusNahledChatRoute
  '/plus/nahled/hlasovky': typeof PlusNahledHlasovkyRoute
  '/plus/nahled/videa': typeof PlusNahledVideaRoute
  '/plus/nahled/zapisky': typeof PlusNahledZapiskyRoute
  '/plus/nahled/': typeof PlusNahledIndexRoute
  '/_authenticated/plus/zapisky/$slug': typeof AuthenticatedPlusZapiskySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/plus'
    | '/reset-password'
    | '/shop'
    | '/plus/checkout'
    | '/plus/nahled'
    | '/product/$handle'
    | '/plus/'
    | '/plus/chat'
    | '/plus/dashboard'
    | '/plus/hlasovky'
    | '/plus/ucet'
    | '/plus/videa'
    | '/plus/zapisky'
    | '/plus/nahled/chat'
    | '/plus/nahled/hlasovky'
    | '/plus/nahled/videa'
    | '/plus/nahled/zapisky'
    | '/plus/nahled/'
    | '/plus/zapisky/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/shop'
    | '/plus/checkout'
    | '/product/$handle'
    | '/plus'
    | '/plus/chat'
    | '/plus/dashboard'
    | '/plus/hlasovky'
    | '/plus/ucet'
    | '/plus/videa'
    | '/plus/zapisky'
    | '/plus/nahled/chat'
    | '/plus/nahled/hlasovky'
    | '/plus/nahled/videa'
    | '/plus/nahled/zapisky'
    | '/plus/nahled'
    | '/plus/zapisky/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/plus'
    | '/reset-password'
    | '/shop'
    | '/plus/checkout'
    | '/plus/nahled'
    | '/product/$handle'
    | '/plus/'
    | '/_authenticated/plus/chat'
    | '/_authenticated/plus/dashboard'
    | '/_authenticated/plus/hlasovky'
    | '/_authenticated/plus/ucet'
    | '/_authenticated/plus/videa'
    | '/_authenticated/plus/zapisky'
    | '/plus/nahled/chat'
    | '/plus/nahled/hlasovky'
    | '/plus/nahled/videa'
    | '/plus/nahled/zapisky'
    | '/plus/nahled/'
    | '/_authenticated/plus/zapisky/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlusRoute: typeof PlusRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  ProductHandleRoute: typeof ProductHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus': {
      id: '/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof PlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus/': {
      id: '/plus/'
      path: '/'
      fullPath: '/plus/'
      preLoaderRoute: typeof PlusIndexRouteImport
      parentRoute: typeof PlusRoute
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus/nahled': {
      id: '/plus/nahled'
      path: '/nahled'
      fullPath: '/plus/nahled'
      preLoaderRoute: typeof PlusNahledRouteImport
      parentRoute: typeof PlusRoute
    }
    '/plus/checkout': {
      id: '/plus/checkout'
      path: '/checkout'
      fullPath: '/plus/checkout'
      preLoaderRoute: typeof PlusCheckoutRouteImport
      parentRoute: typeof PlusRoute
    }
    '/plus/nahled/': {
      id: '/plus/nahled/'
      path: '/'
      fullPath: '/plus/nahled/'
      preLoaderRoute: typeof PlusNahledIndexRouteImport
      parentRoute: typeof PlusNahledRoute
    }
    '/plus/nahled/zapisky': {
      id: '/plus/nahled/zapisky'
      path: '/zapisky'
      fullPath: '/plus/nahled/zapisky'
      preLoaderRoute: typeof PlusNahledZapiskyRouteImport
      parentRoute: typeof PlusNahledRoute
    }
    '/plus/nahled/videa': {
      id: '/plus/nahled/videa'
      path: '/videa'
      fullPath: '/plus/nahled/videa'
      preLoaderRoute: typeof PlusNahledVideaRouteImport
      parentRoute: typeof PlusNahledRoute
    }
    '/plus/nahled/hlasovky': {
      id: '/plus/nahled/hlasovky'
      path: '/hlasovky'
      fullPath: '/plus/nahled/hlasovky'
      preLoaderRoute: typeof PlusNahledHlasovkyRouteImport
      parentRoute: typeof PlusNahledRoute
    }
    '/plus/nahled/chat': {
      id: '/plus/nahled/chat'
      path: '/chat'
      fullPath: '/plus/nahled/chat'
      preLoaderRoute: typeof PlusNahledChatRouteImport
      parentRoute: typeof PlusNahledRoute
    }
    '/_authenticated/plus/zapisky': {
      id: '/_authenticated/plus/zapisky'
      path: '/plus/zapisky'
      fullPath: '/plus/zapisky'
      preLoaderRoute: typeof AuthenticatedPlusZapiskyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plus/videa': {
      id: '/_authenticated/plus/videa'
      path: '/plus/videa'
      fullPath: '/plus/videa'
      preLoaderRoute: typeof AuthenticatedPlusVideaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plus/ucet': {
      id: '/_authenticated/plus/ucet'
      path: '/plus/ucet'
      fullPath: '/plus/ucet'
      preLoaderRoute: typeof AuthenticatedPlusUcetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plus/hlasovky': {
      id: '/_authenticated/plus/hlasovky'
      path: '/plus/hlasovky'
      fullPath: '/plus/hlasovky'
      preLoaderRoute: typeof AuthenticatedPlusHlasovkyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plus/dashboard': {
      id: '/_authenticated/plus/dashboard'
      path: '/plus/dashboard'
      fullPath: '/plus/dashboard'
      preLoaderRoute: typeof AuthenticatedPlusDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plus/chat': {
      id: '/_authenticated/plus/chat'
      path: '/plus/chat'
      fullPath: '/plus/chat'
      preLoaderRoute: typeof AuthenticatedPlusChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plus/zapisky/$slug': {
      id: '/_authenticated/plus/zapisky/$slug'
      path: '/$slug'
      fullPath: '/plus/zapisky/$slug'
      preLoaderRoute: typeof AuthenticatedPlusZapiskySlugRouteImport
      parentRoute: typeof AuthenticatedPlusZapiskyRoute
    }
  }
}

interface AuthenticatedPlusZapiskyRouteChildren {
  AuthenticatedPlusZapiskySlugRoute: typeof AuthenticatedPlusZapiskySlugRoute
}

const AuthenticatedPlusZapiskyRouteChildren: AuthenticatedPlusZapiskyRouteChildren =
  {
    AuthenticatedPlusZapiskySlugRoute: AuthenticatedPlusZapiskySlugRoute,
  }

const AuthenticatedPlusZapiskyRouteWithChildren =
  AuthenticatedPlusZapiskyRoute._addFileChildren(
    AuthenticatedPlusZapiskyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPlusChatRoute: typeof AuthenticatedPlusChatRoute
  AuthenticatedPlusDashboardRoute: typeof AuthenticatedPlusDashboardRoute
  AuthenticatedPlusHlasovkyRoute: typeof AuthenticatedPlusHlasovkyRoute
  AuthenticatedPlusUcetRoute: typeof AuthenticatedPlusUcetRoute
  AuthenticatedPlusVideaRoute: typeof AuthenticatedPlusVideaRoute
  AuthenticatedPlusZapiskyRoute: typeof AuthenticatedPlusZapiskyRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPlusChatRoute: AuthenticatedPlusChatRoute,
  AuthenticatedPlusDashboardRoute: AuthenticatedPlusDashboardRoute,
  AuthenticatedPlusHlasovkyRoute: AuthenticatedPlusHlasovkyRoute,
  AuthenticatedPlusUcetRoute: AuthenticatedPlusUcetRoute,
  AuthenticatedPlusVideaRoute: AuthenticatedPlusVideaRoute,
  AuthenticatedPlusZapiskyRoute: AuthenticatedPlusZapiskyRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PlusNahledRouteChildren {
  PlusNahledChatRoute: typeof PlusNahledChatRoute
  PlusNahledHlasovkyRoute: typeof PlusNahledHlasovkyRoute
  PlusNahledVideaRoute: typeof PlusNahledVideaRoute
  PlusNahledZapiskyRoute: typeof PlusNahledZapiskyRoute
  PlusNahledIndexRoute: typeof PlusNahledIndexRoute
}

const PlusNahledRouteChildren: PlusNahledRouteChildren = {
  PlusNahledChatRoute: PlusNahledChatRoute,
  PlusNahledHlasovkyRoute: PlusNahledHlasovkyRoute,
  PlusNahledVideaRoute: PlusNahledVideaRoute,
  PlusNahledZapiskyRoute: PlusNahledZapiskyRoute,
  PlusNahledIndexRoute: PlusNahledIndexRoute,
}

const PlusNahledRouteWithChildren = PlusNahledRoute._addFileChildren(
  PlusNahledRouteChildren,
)

interface PlusRouteChildren {
  PlusCheckoutRoute: typeof PlusCheckoutRoute
  PlusNahledRoute: typeof PlusNahledRouteWithChildren
  PlusIndexRoute: typeof PlusIndexRoute
}

const PlusRouteChildren: PlusRouteChildren = {
  PlusCheckoutRoute: PlusCheckoutRoute,
  PlusNahledRoute: PlusNahledRouteWithChildren,
  PlusIndexRoute: PlusIndexRoute,
}

const PlusRouteWithChildren = PlusRoute._addFileChildren(PlusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PlusRoute: PlusRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  ProductHandleRoute: ProductHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
